title: Hari's online
author: Arianna Masciolini
email: arianna.masciolini@gmail.com
description: > 
  My homepage
# social links
github_username:  harisont
logo: identicon.png

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme