title: Hari's online
author: 
  name: Arianna Masciolini
  email: arianna.masciolini@gmail.com
description: > 
  A chaotically multilingual blog by Arianna Masciolini

header_pages:
  - about.md
  - projects.md

show_excerpts: false
remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%-d %B %Y"
  social_links:
    github: harisont
    stackoverflow: "7729724"
    telegram: harisont
    instagram: unottica
    youtube_channel: UC6fKcYGimkXYd-N5ryesKqw